version: "1"

grype:
  cveRiskAcceptance:
    enabled: true
    cves:
      # Grype mis-reports this vulnerability which was fixed in clamav >= 0.99.0 even though the apk installed version is >= 1.2.2
      - id: CVE-2016-1405
      # Docker CLI issue only affects Windows
      - id: CVE-2025-15558

semgrep:
  impactRiskAcceptance:
    enabled: true
    low: true
  severityLimit:
    error:
      # Do not error on semgrep findings. There is currently no way to ignore specific semgrep rules or finding instances.
      enabled: false
    warning:
      enabled: true
      limit: 0
