name: Portage Image Build
run-name: "Build, Scan, and Push Portage: ${{ github.event.head_commit.message }}"
permissions:
  contents: read
  checks: write
  packages: write
on:
  workflow_dispatch:
  push:
    branches:
      - '*main'
      - 'debug-*'
    tags: [ '*' ]
    paths: &build_paths
      - .github/workflows/delivery.yaml
      - Dockerfile
      - go.*
      - cmd/**
      - docker/**
      - pkg/**
      - portage.yml
      - .*gatecheck.yml
  pull_request:
    paths: *build_paths

jobs:
  image_build:
    strategy:
      matrix:
        include:
          - arch: 'amd64'
            runs-on: ubuntu-latest
          - arch: 'arm64'
            runs-on: ubuntu-24.04-arm

    name: Build, Scan, and Publish Images for ${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          driver: 'docker-container'

      - name: Load Docker Cache
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/.docker-cache
          key: ${{ runner.os }}-${{ matrix.arch }}-docker-cache

      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6

      - name: Set variables
        id: vars
        run: |
          image_repo=ghcr.io/easy-up/portage
          image_arch=${{ matrix.arch }}
          image_tag=${GITHUB_SHA::8}
          # If on a git tag like vx.x.x, change the image tag to reflect
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            image_tag=${GITHUB_REF/refs\/tags\//}
          fi
          # Image Names
          echo "image_name=$image_repo:$image_arch-$image_tag" >> $GITHUB_OUTPUT
          echo "podman_image_name=$image_repo:podman-$image_arch-$image_tag" >> $GITHUB_OUTPUT
          # Build Variables
          echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
          echo "git_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "git_description=$(git log -1 --pretty=%B | head -n 1 | tr \' _)" >> $GITHUB_OUTPUT

      - name: Build, Scan, and Publish Images (Docker CLI)
        uses: easy-up/portage-cd-actions/image-build-scan-publish/docker@buildkit-debug
        with:
          platform: linux/${{ matrix.arch }}
          tag: ${{ steps.vars.outputs.image_name }}
          build_args: "VERSION=${{ steps.vars.outputs.version }},GIT_COMMIT=${{ steps.vars.outputs.git_commit }},GIT_DESCRIPTION=${{ steps.vars.outputs.git_description }}"
          image_build_cache_from: "type=local,src=${{ runner.temp }}/.docker-cache"
          image_build_cache_to: "type=local,dest=${{ runner.temp }}/.docker-cache,mode=max"
          deploy_enabled: true

      - name: Build, Scan, and Publish Images (Podman CLI)
        uses: easy-up/portage-cd-actions/image-build-scan-publish/docker@buildkit-debug
        with:
          platform: linux/${{ matrix.arch }}
          tag: ${{ steps.vars.outputs.podman_image_name }}
          target: portage-podman
          build_args: "VERSION=${{ steps.vars.outputs.version }},GIT_COMMIT=${{ steps.vars.outputs.git_commit }},GIT_DESCRIPTION=${{ steps.vars.outputs.git_description }}"
          image_build_cache_from: "type=local,src=${{ runner.temp }}/.docker-cache"
          image_build_cache_to: "type=local,dest=${{ runner.temp }}/.docker-cache,mode=max"
          deploy_enabled: true

      - name: Store Artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts-${{ matrix.arch }}
          path: artifacts/

      - name: Push Docker Images
        run: |
          docker push ${{ steps.vars.outputs.image_name }}
          docker push ${{ steps.vars.outputs.podman_image_name }}

      - name: job summary
        shell: bash
        run: |
          echo "## Docker Action Image Build and Push Summary" >> $GITHUB_STEP_SUMMARY
          echo ":white_check_mark: Image (Docker CLI): ${{ steps.vars.outputs.image_name }}" >> $GITHUB_STEP_SUMMARY
          echo ":white_check_mark: Image (Podman CLI): ${{ steps.vars.outputs.podman_image_name }}" >> $GITHUB_STEP_SUMMARY

  push_manifest:
    needs: image_build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: vars
        run: |
          IMAGE_REPO=ghcr.io/easy-up/portage
          IMAGE_TAG=${GITHUB_SHA::8}
          # If on a git tag like vx.x.x, change the image tag to reflect
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            IMAGE_TAG=${GITHUB_REF/refs\/tags\//}
          fi
          # Image Names
          echo "amd64_image_name=$IMAGE_REPO:amd64-$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "arm64_image_name=IMAGE_REPO:arm64-$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_REPO:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "podman_amd64_image_name=$IMAGE_REPO:podman-amd64-$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "podman_arm64_image_name=$IMAGE_REPO:podman-arm64-$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "podman_image_name=$IMAGE_REPO:podman-$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Create and push manifest
        run: |
          docker manifest create "${{ steps.vars.outputs.image_name }}" \
            --amend "${{ steps.vars.outputs.amd64_image_name }}" \
            --amend "${{ steps.vars.outputs.arm64_image_name }}"
          docker manifest push "${{ steps.vars.outputs.image_name }}"
          docker manifest create "${{ steps.vars.outputs.podman_image_name }}" \
            --amend "${{ steps.vars.outputs.podman_amd64_image_name }}" \
            --amend "${{ steps.vars.outputs.podman_arm64_image_name }}"
          docker manifest push "${{ steps.vars.outputs.podman_image_name }}"
  
